### PR TITLE
Updated to ASP.NET 5 RC1

### PR DESCRIPTION
**Pull request by vnbaaij**

### CODE REVIEW

**Comment by Shazwazza** [comment]
brilliant! i'll have a look later today, just upgrading Smidge to rc1 now

**Comment by Shazwazza** [comment]
Finally getting around to some of this, thanks again!

**Comment by vnbaaij** [comment]
You're welcome. Curious to see how quick this will go

**Comment by Shazwazza** [comment]
well v8 needs to be made/released before v9 can actually work but i'll be tinkering away with v9 when I have some time for specific aspnetcore functionality that will need to be implemented differently than nromal aspnet

**Pull request merged**
